Update ping.yml
+++

diff --git a/.github/workflows/ping.yml b/.github/workflows/ping.yml
--- a/.github/workflows/ping.yml
+++ b/.github/workflows/ping.yml
@@ -1,14 +1,14 @@
-name: Keep Bot Alive
+name: Keep bot alive
 
 on:
   schedule:
-    - cron: '*/5 * * * *'
+    - cron: '*/10 * * * *'
   workflow_dispatch:
 
 jobs:
   ping:
     runs-on: ubuntu-latest
     steps:
-      - name: Ping Telegram Bot
-        run: |
-          curl -s -o /dev/null -w "%{http_code}\n" https://ansamb-sledov6-bot.onrender.com/
+    - name: Ping
+      run: |
+        curl -I https://ansamb-sledov-bot-94wz.onrender.com/ping || echo "failed"
